import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <Container maxWidth="lg">
        <Box
          width={800}
          height={800}
          bgcolor={'secondary.main'}
          m={20}
          sx={{
            boxShadow: '0px 0px 100px 30px rgba(168, 105, 240, 0.3)',
            borderRadius: '40px',
          }}
        ></Box>
      </Container>
    </>
  );
}
