import { Inter } from 'next/font/google';
import { FilmCards } from '@/widgets/FilmCards/FilmCards';
import Head from 'next/head';
import mgr, { Film, FilmsManager } from '@/types/film';
import { useState, useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="/normalize.css"
        />
      </Head>
      <h2>Современные мультфильмы</h2>
      <FilmCards films={mgr.films} />
    </div>
  );
}
